name: CI/CD Pipeline

# Triggers for CI: push and pull requests to main.
# Triggers for CD: when a release is published.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies for linting
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint Code
        run: flake8 .

      - name: Check Python Syntax
        # Replace 'your_script.py' with the actual filename
        run: python -m py_compile your_script.py

  cd:
    # CD job runs only on release events
    if: github.event_name == 'release'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Package the project
        # Here, we assume you have a packaging step.
        # For a simple script, you might just zip the file.
        run: |
          mkdir artifact
          cp your_script.py artifact/
          cd artifact && zip ../artifact.zip your_script.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: artifact.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
